config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/index'

  get 'restaurants/new'

  get 'restaurants/create'

  get 'restaurants/show'

  # # READ
  # # READ ALL
  get "restaurants", to: "restaurants#index"

  #  # CREATE
  # # Permet d'afficher le formulaire à remplir
  get "restaurants/new", to: "restaurants#new"

  # # Permet de soumettre les champs remplis par l'user
  post "restaurants", to: "restaurants#create"

  # # READ ONE
  get "restaurants/:id", to: "restaurants#show", as: :restaurant

  # # UPDATE
  # # Donner le formulaire à modifier
  # get "restaurants/:id/edit", to: "restaurants#edit", as: :edit
  # # Soummetre les modifs et enregistrer
  # patch "restaurants/:id", to: "restaurants#update"

  # # DELETE
  # delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
    has_many :reviews, dependent: :destroy
    validates :address, presence: true
    validates :name, presence: true
    validates :category, inclusion: { in: CATEGORIES,
    message: "%{value} is not a valid category" }
end


# A restaurant must have at least a name and an address. OK
# The restaurant category should belong to a fixed list ["chinese", "italian", "japanese", "french", "belgian"]. OK

# A review must have a parent restaurant.

# When a restaurant is destroyed, all of its reviews should be destroyed as well.

app/models/review.rb
class Review < ApplicationRecord
  RATING = 0..5
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: RATING,
  message: "%{value} is not a valid category" }
end

# A review must have content and a rating. The rating should be a number between 0 and 5.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show] #, :edit, :update, :destroy]

  def index
    #on récupère un array d'instances
    @restaurants = Restaurant.all
  end
  def show
    # 1 seul
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    # raise
    @restaurant.save
    redirect_to restaurants_path
  end
  # def edit
  # end
  # def update
  #   @restaurant.update(restaurant_params)
  #   redirect_to restaurant_path(@restaurant)
  # end
  # def destroy
  #   @restaurant.destroy
  #   redirect_to restaurants_path
  # end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Tous les restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <li><%= restaurant.address %></li>
  <% end %>
</ul>

<%= link_to "Créez votre resto", restaurants_new_path %>

app/views/restaurants/new.html.erb
<h1>Nouveau resto</h1>

<%= render 'shared/form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h1><%= @restaurant.address %></h1>
<h1><%= link_to "Retour à la liste", restaurants_path %></h1>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= simple_form_for(restaurant, html: { class: 'input-group' }) do |f| %>
      <%= f.input :name, label: 'The restaurant name :' %>
      <%= f.input :address, label: 'Address ? :' %>
      <%= f.input :category, label: 'Sa category :', collection: Restaurant::CATEGORIES  %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>